repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: fmt_rust
        name: fmt_rust
        entry: bash -c 'rustfmt core_lib/**.rs frontend/src-tauri/**.rs'
        language: system
