[package]
name = "rquickshare"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "core_bin"
path = "src/bin.rs"

[dependencies]
anyhow = "1.0"
base64 = "0.21"
btleplug = "0.11.5"
directories = "5.0"
futures = "0.3.30"
hex = "0.4"
hkdf = "0.12"
hmac = "0.12"
libaes = "0.7"
log = "0.4"
mdns-sd = { git = "https://github.com/Martichou/mdns-sd", branch = "unsolicited" }
once_cell = "1.0"
open = "5.0"
p256 = { version = "0.13", features = ["ecdh"] }
prost = "0.12"
rand = "0.8"
sha2 = "0.10"
sys_metrics = "0.2"
tokio = { version = "1.25", features = ["macros", "rt", "rt-multi-thread", "net", "sync", "time", "io-util", "signal"] }
tokio-util = { version = "0.7", features = ["rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = "1.7.0"

[build-dependencies]
prost-build = "0.12"
