name: Build-(Core & Tauri)

on:
  push:
    branches: [ "master" ]
  pull_request:

# cancel ongoing jobs:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/core_lib/target"
      - uses: arduino/setup-protoc@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev
      - run: |
          cd ./core_lib
          cargo test
          cargo build

  build_tauri:
    runs-on: ${{ matrix.os }}
    needs: build_core
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target_path: app/legacy
            dependencies: |
              sudo apt-get install -y libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
            cache_directory: app/legacy/src-tauri/target
          - os: ubuntu-24.04
            target_path: app/main
            dependencies: |
              sudo apt-get install -y libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev
            cache_directory: app/main/src-tauri/target
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/${{ matrix.cache_directory }}"
      - uses: arduino/setup-protoc@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Linux dependencies for U
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libgtk-3-dev
      - name: Install Linux dependencies
        run: ${{ matrix.dependencies }}
      - name: GLIBC version
        run: ldd --version
      - name: Build Vite + Tauri
        run: |
          cd ./${{ matrix.target_path }}
          pnpm deb:build
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: artifact-debug-rquickshare
          path: |
            ${{ github.workspace }}/${{ matrix.target_path }}/src-tauri/target/debug/bundle/appimage/r-quick-share*.AppImage