name: Build-(Core & Tauri)

on:
  push:
    branches: [ "master" ]
  pull_request:

# cancel ongoing jobs:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_core:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/core_lib/target"
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        if: contains(matrix.os, 'macos') == false
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev
      - run: |
          cd ./core_lib
          cargo test
          cargo build

  build_tauri:
    runs-on: ${{ matrix.os }}
    needs: build_core
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target_path: app/legacy
            dependencies: |
              sudo apt-get install -y libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
            cache_directory: app/legacy/src-tauri/target
            generated_bundle: appimage/r-quick-share*.AppImage
          - os: ubuntu-24.04
            target_path: app/main
            dependencies: |
              sudo apt-get install -y libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev
            cache_directory: app/main/src-tauri/target
            generated_bundle: appimage/r-quick-share*.AppImage
          - os: macos-latest
            target_path: app/main
            cache_directory: app/main/src-tauri/target
            generated_bundle: dmg/RQuickShare_*.dmg
          - os: macos-13
            target_path: app/main
            cache_directory: app/main/src-tauri/target
            generated_bundle: dmg/RQuickShare_*.dmg
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/${{ matrix.cache_directory }}"
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Linux dependencies for U
        if: contains(matrix.os, 'macos') == false
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Install Linux dependencies
        if: contains(matrix.os, 'macos') == false
        run: ${{ matrix.dependencies }}
      - name: GLIBC version
        if: contains(matrix.os, 'macos') == false
        run: |
          GLIBC_VER=$(ldd --version | head -n1 | awk '{print $NF}')
          echo "GLIBC version: ${GLIBC_VER}"
      - name: Build Vite + Tauri
        run: |
          cd ./${{ matrix.target_path }}
          pnpm install
          pnpm build:debug
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: artifact-debug-rquickshare-${{ matrix.os }}
          path: |
            ${{ github.workspace }}/${{ matrix.target_path }}/src-tauri/target/debug/bundle/${{ matrix.generated_bundle }}