name: Clippy

on:
  push:
    branches: [ "master" ]
  pull_request:

# cancel ongoing jobs:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: ./core_lib
            clippy_args: "--all-features --all"
          - directory: ./frontend/src-tauri
            clippy_args: "--no-default-features"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev
      - name: Install Linux dependencies
        if: matrix.directory == './frontend/src-tauri'
        run: |
          sudo apt-get install -y libjavascriptcoregtk-4.1-dev libdbus-1-dev libgtk-4-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Clippy Check
        run: |
          cd ${{ matrix.directory }}
          cargo clippy ${{ matrix.clippy_args }}