name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:

# cancel ongoing jobs:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  stylerust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - directory: ./core_lib
          - directory: ./frontend/src-tauri
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          cd ${{ matrix.directory }}
          cargo fmt --all --check
  style_tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd ./frontend
          pnpm lint
