name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
  push:
    tags:
      - '*'

jobs:
  build_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: legacy
            target_path: app/legacy
            dependencies: |
              sudo apt-get install -y libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.0-dev
            cache_directory: app/legacy/src-tauri/target
          - os: ubuntu-24.04
            name: main
            target_path: app/main
            dependencies: |
              sudo apt-get install -y libsoup-3.0-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev
            cache_directory: app/main/src-tauri/target
    steps:
      - name: Extract version number
        run: |
          TAG=${{ github.ref_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Print version number
        run: |
          echo "Version number: ${{ env.VERSION }}"

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "${{ github.workspace }}/${{ matrix.cache_directory }}"
      - uses: arduino/setup-protoc@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Linux dependencies for U
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev libgtk-3-dev
      - name: Install Linux dependencies
        run: ${{ matrix.dependencies }}

      - name: Build Vite + Tauri
        run: |
          cd ./${{ matrix.target_path }}
          pnpm build
          GLIBC_VER=$(ldd --version | head -n1 | awk '{print $NF}')
          echo "GLIBC version: ${GLIBC_VER}"
          for file in ${{ github.workspace }}/${{ matrix.target_path }}/src-tauri/target/release/bundle/*/r-quick-share*; do
            extension="${file##*.}"
            if [[ ! -f "$file" ]] || [[ "$extension" == AppDir ]]; then
              echo "Skipping $file"
              continue
            fi
            new_name="${file%.*}_${{ matrix.name }}_glibc-${GLIBC_VER}.$extension"
            mv "$file" "$new_name"
            echo "Renamed $file to $new_name"
          done

      - uses: snapcore/action-build@v1
        if: matrix.target_path == 'app/legacy'
        id: build-snap
      - run: sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}
        if: matrix.target_path == 'app/legacy'
      - name: Set Snap File Path
        if: matrix.target_path == 'app/legacy'
        run: echo "SNAP_FILE=${{ steps.build-snap.outputs.snap }}" >> $GITHUB_ENV

      - name: Add files to release
        if: github.event_name != 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/${{ matrix.target_path }}/src-tauri/target/release/bundle/*/r-quick-share_${{ env.VERSION }}*
            ${{ env.SNAP_FILE }}
          fail_on_unmatched_files: true

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: artifact-debug-rquickshare
          path: |
            ${{ github.workspace }}/${{ matrix.target_path }}/src-tauri/target/release/bundle/*/r-quick-share_${{ env.VERSION }}*
            ${{ env.SNAP_FILE }}
